services:
  dns-blm.api:
    image: dns-blm.api
    build:
      context: .
      dockerfile: src/DNS-BLM.Api/Dockerfile
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Zurich
      - DNS-BLM__TimedTasks__ScanBlacklistProviders=0 2 * * * # Executed daily at 2am
      - DNS-BLM__Domains__0=example1.com
      - DNS-BLM__Domains__1=example2.com
      - DNS-BLM__Domains__2=example3.com
