name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lowercase repository name
        id: lowercase
        run: echo "repo_lower=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/DNS-BLM.Api/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ steps.lowercase.outputs.repo_lower }}:dev
