name: Build and Push Docker Image on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write # Ensure this permission is set

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lowercase repository name
        id: lowercase
        # Use GITHUB_REPOSITORY variable which is owner/repo
        run: echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version components and generate tags
        id: semver_tags
        run: |
          ref_name="${{ github.ref_name }}"
          version="${ref_name#v}"
          major=$(echo "$version" | cut -d. -f1)
          major_minor=$(echo "$version" | cut -d. -f1,2)
          image_base="ghcr.io/${{ steps.lowercase.outputs.repo_lower }}"
          tags=$(cat <<EOF
          ${image_base}:${major}
          ${image_base}:${major_minor}
          ${image_base}:${version}
          EOF
          )
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "$tags" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Generated tags:" # Optional: Log the tags for debugging
          echo "$tags"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6 # Use latest version
        with:
          context: .
          file: ./src/DNS-BLM.Api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          # Use the output from the semver_tags step
          tags: ${{ steps.semver_tags.outputs.tags }}
